Controllers/CohortsController.cs
using Microsoft.AspNetCore.Mvc;

namespace DatovyPortalWeb.Controllers {
    public class CohortsController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DatovyPortalApp.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DatovyPortalApp.Services;
using DatovyPortalApp.ViewModels;

namespace DatovyPortal.Controllers {


    public class DataController : Controller {
        private readonly DataService service;

        public DataController(DataService dataService) {
            this.service = dataService;
        }

        [Route("/Data/Index/{indicator:int=1}")]
        public async Task<IActionResult> Index(int indicator = 1) {

            var selectedIndicator = await service.GetSelectedIndicatorAsync(indicator);
            if (selectedIndicator == null) {
                return View("NotFound");
            }
            ViewBag.SelectedIndicator = selectedIndicator;
            ViewBag.Sets = await service.GetSetCodeListAsync();
            ViewBag.Indicators = await service.GetIndicatorCodeListAsync(); ;
            ViewBag.SelectedDiagnoses = await service.GetSelectedDiagnosesAsync(indicator);
            ViewBag.SelectedStadiums = await service.GetSelectedStadiumsAsync(indicator);
            ViewBag.SelectedRegions = await service.GetSelectedRegionsAsync(indicator);
            ViewBag.SelectedPeriods = await service.GetSelectedPeriodsAsync(indicator);
            ViewBag.SelectedStatistics = await service.GetSelectedStatisticsAsync(indicator);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ValuesOutput(DataToOutputViewModel inputViewModel, int indicator) {
            ValuesOutputViewModel outputViewModel = await service.GetValuesOutputAsync(inputViewModel, indicator);

            return PartialView("_ValuesOutput", outputViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GraphOutput(DataToOutputViewModel inputViewModel, int indicator) {
            GraphOutputViewModel graphViewModel = await service.GetGraphOutputAsync(inputViewModel, indicator);
            
            return PartialView("_GraphOutput", graphViewModel);
        }
    }
}

Controllers/SourcesController.cs
using Microsoft.AspNetCore.Mvc;

namespace DatovyPortalWeb.Controllers {
    public class SourcesController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Datový portál ÚsZI</title>    
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/scss/site.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js" charset="utf-8"></script>
    <script src="~/js/site.js"></script>
</head>
<body>
    <header class="mb-5">
        <nav class="navbar bg-primary navbar-expand-sm navbar-toggleable-sm fixed-top" data-bs-theme="dark">
            <div class="container-fluid">
                <span class="navbar-brand d-inline d-sm-none">Datový portál ÚsZI</span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>                    
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link link-light link-opacity-75-hover" asp-area="" asp-controller="Home" asp-action="Index">O datovém portálu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light link-opacity-75-hover" asp-area="" asp-controller="Data" asp-action="Index">Indikátory kvality péče</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link link-light link-opacity-75-hover" asp-area="" asp-controller="Cohorts" asp-action="Index">Definice kohort pacientů</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light link-opacity-75-hover" asp-area="" asp-controller="Sources" asp-action="Index">Zdroje dat</a>
                        </li>*@
                    </ul>                    
                </div>
                <span class="navbar-brand d-none d-sm-inline">Datový portál ÚsZI</span>
            </div>
        </nav>
    </header>

    <main role="main">
        @RenderBody()
    </main>

    @*<footer class="container-fluid">
        <p class="text-center mt-3">&copy; Martina Uhrová, 2023</p>
    </footer>*@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*@await RenderSectionAsync("Graphs", required: false)*@
</body>
</html>